apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5T9h2EoNu+M7lpbhOL9AdcDcm84uIMVU9xJYGcE4fEsV9KaLYAej3ZiVOeJoNn+4hXM9DeP2sx0wu9t1axKJIP/YY6WzgS7Vrtxv5a4d4o0FyNR/lZFsQyLVV6NQku1d2SzxwPMX76YJMboTtbDsvxIf83JnvowKVp7I8PyFq+60sOq2zbX2ZwNj4B4cJgFNsMhnZj6w+dTPErMPd/+wr1zJE8kdWDiaT6JDSkHC4SUrLCYrBAaVxyUASpSXMd+1CxXuit/h1Pw2ZKABmeIRea2ZKKy8K/3AlTbUXLpVqtLr8EQrZW1EFAePb7EdW+p6kt/Q2KnAliJaXsHytsvlXwJgZBAUKr73JPdi270h27Qydp/i7WBArqmlZ70=,iv:UxK14aBcxdYRu4L71abC+F/z3qzHKecYBSj/m6amsns=,tag:wJhnaN2U/HNWUEuETb/jqA==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: homepage
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S2FSaG9mL3UwZWRKcHNE
            bGFPbzlVN0lieTYrYzQyZHVPM1pKWENqaWhVCnVlYWM4L2x4ZnVFMlZZVFZRbys2
            M1dsd0tmejVnZXZtdUpMZ01wV1JxKzQKLS0tIDlSbUJoQ0F6ZllLb2JKcjFsMGI0
            Sjk2TkN2aXRBdXRUVnhISnE2ZkIzZlEKTvrsQEAWZJkJFYjiSQN0P+JECt9JWpQe
            tuakORGYl5OlsWj70DH2Scxzq2KlarYeaO85iNKRUYaaMAcC78no1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-15T10:42:53Z"
    mac: ENC[AES256_GCM,data:92Kup0vXnUJJjOzi0IQMuyQv3ONaJjPlhEKbAre+caphvF+L5e5USVBYZFHMGxSuYikIawp7yDdHii22aq4N2r28V1JRG211YCJ1VzUGfXS3Oq2rG2wxNOK0DjHKhY+v+BdWISFpdQqUmePHOcdr8zLzaOkxsRgBD/jdimdk7ms=,iv:YeAjVUMnYGCVwuGH99h2xIthcoF8jsrhVyVovqmTuh8=,tag:+5wqaqIIGyWd7CX1g5QGcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
