---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pterodactyl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pterodactyl-secret
    creationPolicy: Owner
    template:
      data:
        DB_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: Pterodactyl
