apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: &db pterodactyl
spec:
  mariaDbRef:
    name: mariadb-galera
    namespace: database
  privileges:
    - "ALL PRIVILEGES"
  database: *db
  table: '*'
  username: *db
