apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: pterodactyl
spec:
  mariaDbRef:
    name: mariadb-galera
    namespace: database
  passwordSecretKeyRef:
    name: pterodactyl-secret
    key: DB_PASSWORD
  maxUserConnections: 20
