---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiomuse
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      audiomuse:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
            envFrom: &env
              - secretRef:
                  name: audiomuse-secret
        containers:
          main:
            image: &image
              repository: ghcr.io/neptunehub/audiomuse-ai
              tag: 2.1.4@sha256:04d1c5b8c6c766a26ca2ef008c2b7e6f5f0a1e93590176f7d68ead0048d4c4dd
            env:
              SERVICE_TYPE: "flask"
              TZ: ${TIMEZONE}
              REDIS_URL: &redis redis://dragonfly.database.svc:6379/9
              TEMP_DIR: &tempdir "/app/temp_audio"
            envFrom: *env
      worker:
        replicas: 3
        type: statefulset
        containers:
          main:
            image: *image
            env:
              SERVICE_TYPE: "worker"
              TZ: ${TIMEZONE}
              REDIS_URL: *redis
              TEMP_DIR: *tempdir
            envFrom: *env
    service:
      main:
        controller: audiomuse
        ports:
          http:
            port: &port 8000
    route:
      main:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    defaultPodOptions:
      enableServiceLinks: true
      securityContext:
        runAsUser: ${NAS_UID}
        runAsGroup: ${NAS_GID}
        fsGroup: ${NAS_GID}
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
    podAnnotations:
      secret.reloader.stakater.com/reload: audiomuse
    persistence:
      tempaudio:
        enabled: true
        type: emptyDir
        advancedMounts:
          audiomuse:
            main:
              - path: *tempdir
          worker:
            main:
              - path: *tempdir
