---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pterodactyl
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pterodactyl:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/pterodactyl/panel
              tag: v1.11.11@sha256:3ad185c83818944cfd4dba4dcefbca5ffb64655aaa63363f8f76ce41cd19873f
            env:
              DB_HOST: mariadb-galera.database.svc.cluster.local
              DB_PORT: 3306
              DB_DATABASE: *app
              DB_USERNAME: *app
              REDIS_HOST: dragonfly.database.svc.cluster.local
              CACHE_DRIVER: "redis"
              SESSION_DRIVER: "redis"
              QUEUE_DRIVER: "redis"
              APP_URL: "https://pterodactyl.${SECRET_DOMAIN}"
              APP_ENV: "production"
              APP_ENVIRONMENT_ONLY: "false"
              APP_TIMEZONE: ${TIMEZONE}
              APP_SERVICE_AUTHOR: me@${SECRET_DOMAIN}
              APP_CORS_ALLOWED_ORIGINS: "*.${SECRET_DOMAIN}"
              TRUSTED_PROXIES: "*"
            envFrom:
              - secretRef:
                  name: pterodactyl-secret
            resources:
              requests:
                cpu: 50m
                memory: 300M
              limits:
                memory: 500M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, OPTIONS"
          nginx.ingress.kubernetes.io/cors-allow-headers: "*"
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          nginx.ingress.kubernetes.io/cors-max-age: "100"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_input_headers X-Forwarded-Proto "https";
            more_set_headers X-Forwarded-Proto "https";
        hosts:
          - host: &host "pterodactyl.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      data:
        enabled: true
        existingClaim: *app
        advancedMounts:
          pterodactyl:
            app:
              - subPath: "data"
                path: "/app/var"
              - subPath: "nginx"
                path: "/etc/nginx/http.d"
              - subPath: "logs"
                path: "/app/storage/logs"

