---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: piped
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: piped-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        PGDATABASE: piped
        PGHOST: &dbHost postgres16-rw.database.svc.cluster.local
        PGUSER: &dbUser "{{ .DATABASE_USER }}"
        PGPASSWORD: &dbPass "{{ .DATABASE_PASSWORD }}"
        config.properties: |
          API_URL: https://piped-api.${SECRET_DOMAIN}
          COMPROMISED_PASSWORD_CHECK: true
          DISABLE_REGISTRATION: false
          FEED_RETENTION: 30
          FRONTEND_URL: https://piped.${SECRET_DOMAIN}
          HTTP_WORKERS: 4
          MATRIX_SERVER: https://matrix-client.matrix.org
          PORT: 8080
          PROXY_PART: https://piped-proxy.${SECRET_DOMAIN}
          SENTRY_DSN:
          hibernate.connection.driver_class: org.postgresql.Driver
          hibernate.connection.url: jdbc:postgresql://postgres16-rw.database.svc.cluster.local:5432/piped
          hibernate.connection.username: {{ .DATABASE_USER }}
          hibernate.connection.password: {{ .DATABASE_PASSWORD }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: piped
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_password }}"
  dataFrom:
    - extract:
        key: Piped
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
