---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: opencloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WEBFINGER_WEB_OIDC_CLIENT_ID: "{{ .OPENCLOUD_CLIENT_ID }}"
        WEBFINGER_ANDROID_OIDC_CLIENT_ID: "{{ .OPENCLOUD_CLIENT_ID }}-android"
        WEBFINGER_IOS_OIDC_CLIENT_ID: "{{ .OPENCLOUD_CLIENT_ID }}-ios"
        WEBFINGER_DESKTOP_OIDC_CLIENT_ID: "{{ .OPENCLOUD_CLIENT_ID }}-desktop"
        STORAGE_USERS_DECOMPOSEDS3_ACCESS_KEY: "{{ .accessKey }}"
        STORAGE_USERS_DECOMPOSEDS3_SECRET_KEY: "{{ .secretKey }}"
  dataFrom:
    - extract:
        key: Opencloud
      rewrite:
        - regexp:
            source: "(.*)"
            target: "OPENCLOUD_$1"
    - extract:
        key: Minio
