---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opencloud
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 4000
            runAsGroup: 4000
            runAsNonRoot: true
            fsGroup: 4000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: docker.io/opencloudeu/opencloud-rolling
              tag: 7.3.0@sha256:f988f14779cbfe26dec78ea3fc2492ae063fe14a069857dd2d5a397a927fc361
            command:
              - "/bin/sh"
              - "-c"
              - "opencloud init || 'true'; opencloud server"
            env:
              OC_URL: &domain "https://oc.${SECRET_DOMAIN}"
              IDM_CREATE_DEMO_USERS: 'false'

              INSECURE: 'true'
              OC_INSECURE: 'true'

              OC_LOG_LEVEL: "info"
              PROXY_TLS: 'false'

              IDP_DOMAIN: 'auth.${SECRET_DOMAIN}'
              OC_OIDC_ISSUER: 'https://auth.${SECRET_DOMAIN}'

              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: 'none'
              PROXY_OIDC_REWRITE_WELLKNOWN: 'true'
              PROXY_AUTOPROVISION_ACCOUNTS: 'true'
              PROXY_AUTOPROVISION_CLAIM_USERNAME: "preferred_username"
              PROXY_AUTOPROVISION_CLAIM_EMAIL: "email"
              PROXY_AUTOPROVISION_CLAIM_DISPLAYNAME: "name"
              PROXY_AUTOPROVISION_CLAIM_GROUPS: "groups"
              PROXY_CSP_CONFIG_FILE_LOCATION: '/etc/opencloud/csp.yaml'

              WEBFINGER_WEB_OIDC_CLIENT_SCOPES: 'openid profile email groups offline_access'
              WEBFINGER_ANDROID_OIDC_CLIENT_SCOPES: 'openid profile email groups offline_access'
              WEBFINGER_IOS_OIDC_CLIENT_SCOPES: 'openid profile email groups offline_access'
              WEBFINGER_DESKTOP_OIDC_CLIENT_SCOPES: 'openid profile email groups offline_access'

              OC_EXCLUDE_RUN_SERVICES: 'idp'
              OC_ADD_RUN_SERVICES: 'collaboration'
              PROXY_ROLE_ASSIGNMENT_DRIVER: 'oidc'
              GRAPH_ASSIGN_DEFAULT_USER_ROLE: 'false'

              STORAGE_USERS_DRIVER: decomposeds3
              STORAGE_SYSTEM_DRIVER: decomposed
              STORAGE_USERS_DECOMPOSEDS3_ENDPOINT: http://rustfs.default.svc:9000
              STORAGE_USERS_DECOMPOSEDS3_REGION: default
              STORAGE_USERS_DECOMPOSEDS3_BUCKET: *app
              STORAGE_USERS_EVENTS_NUM_CONSUMERS: "5"

              COLLABORATION_WOPI_SRC: *domain
              COLLABORATION_APP_NAME: "OnlyOffice"
              COLLABORATION_APP_PRODUCT: "OnlyOffice"
              COLLABORATION_APP_ADDR: https://onlyoffice.${SECRET_DOMAIN}
              COLLABORATION_APP_ICON: https://onlyoffice.${SECRET_DOMAIN}/web-apps/apps/documenteditor/main/resources/img/favicon.ico
              COLLABORATION_APP_INSECURE: 'false'
              COLLABORATION_CS3API_DATAGATEWAY_INSECURE: 'false'
              COLLABORATION_APP_PROOF_DISABLE: 'true'
            envFrom:
              - secretRef:
                  name: opencloud-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: 9200
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/opencloud
            subPath: data
          - path: /etc/opencloud
            subPath: config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
      csp-config:
        type: configMap
        name: opencloud-config
        advancedMounts:
          opencloud:
            app:
              - path: /etc/opencloud/csp.yaml
                subPath: csp.yaml
                readOnly: true
      role-assignments:
        type: configMap
        name: opencloud-config
        advancedMounts:
          opencloud:
            app:
              - path: /etc/opencloud/proxy.yaml
                subPath: roles.yaml
                readOnly: true
    route:
      app:
        hostnames:
          - "oc.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
