---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
    - name: ghost-mariadb
      namespace: default
  values:
    controllers:
      ghost:
        containers:
          app:
            image:
              repository: ghost
              tag: 5.118.0
            env:
              TZ: ${TIMEZONE}
              url: "https://ghost.${SECRET_DOMAIN}"
              database__client: mysql
              database__connection__host: ghost-mariadb.default.svc.cluster.local
              database__connection__user: ghost
              database__connection__database: ghost
              NODE_ENV: production
            envFrom:
              - secretRef:
                  name: ghost-secret
    service:
      app:
        controller: ghost
        ports:
          http:
            port: 2368
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
        hosts:
          - host: &host ghost.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      content:
        enabled: true
        globalMounts:
          - path: /var/lib/ghost/content
        existingClaim: ghost
