---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invidious
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invidious-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        INVIDIOUS_CONFIG: |
          db:
            dbname: invidious
            user: '{{ .DATABASE_USER }}'
            password: '{{ .DATABASE_PASSWORD }}'
            host: postgres16-rw.database.svc
            port: 5432
          external_port: 3000
          domain: 'youtube.${SECRET_DOMAIN}'
          hmac_key: '{{ .INVIDIOUS_HMAC_KEY }}'
          invidious_companion_key: '{{ .INVIDIOUS_COMPANION_KEY }}'
          invidious_companion:
          - private_url: 'http://invidious-companion:8282/companion'
        INIT_POSTGRES_DBNAME: invidious
        INIT_POSTGRES_HOST: postgres16-rw.database.svc
        INIT_POSTGRES_USER: '{{ .DATABASE_USER }}'
        INIT_POSTGRES_PASS: '{{ .DATABASE_PASSWORD }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .CNPG_password }}'
        SERVER_SECRET_KEY: '{{ .INVIDIOUS_COMPANION_KEY }}'
  dataFrom:
    - extract:
        key: Invidious
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
