# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.26.3
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java11
    resources:
      limits:
        memory: 4Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 100
    livenessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - echo
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      TZ: ${TIMEZONE}
      ENABLE_AUTOPAUSE: TRUE # Doesn't work in Kubes
      # PAPER_CHANNEL: experimental
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: &host minecraft.${SECRET_DOMAIN}
    minecraftServer:
      eula: true
      version: "1.14.4"
      type: PAPER
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 4096M
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      ops: "SW33"
      motd: "Diversity 3"
      downloadWorldUrl: https://mediafilez.forgecdn.net/files/2914/377/DIVERSITY%203%20PACKAGE%20v1.6.6.zip
      viewDistance: 12
      enableCommandBlock: true
      rcon:
        enabled: true
  # valuesFrom:
  # - kind: Secret
  #   name: minecraft-create-secret
  #   valuesKey: RCON_PASSWORD
  #   targetPath: minecraftServer.rcon.password
