[env]
_.file = '.env'
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
MC_INSECURE="true"

[tools]
"python" = "3.14.5"
"pipx:makejinja" = "2.8.1"
"github:budimanjojo/talhelper" = "3.1.10"
"github:cilium/cilium-cli" = "0.19.2"
"github:cli/cli" = "2.82.1"
"github:cloudflare/cloudflared" = "2025.10.1"
"github:cue-lang/cue" = "0.14.2"
"github:FiloSottile/age" = "1.2.1"
"github:fluxcd/flux2" = "2.8.7"
"github:getsops/sops" = "3.13.1"
"github:go-task/task" = "3.50.0"
"github:helm/helm" = "4.2.0"
"github:helmfile/helmfile" = "1.3.2"
"github:jqlang/jq" = "1.8.1"
"github:kubernetes-sigs/kustomize" = "5.7.0"
"github:mikefarah/yq" = "4.48.1"
"github:siderolabs/talos" = "1.12.7"
"github:yannh/kubeconform" = "0.7.0"
opentofu = "1.10.6"
k9s = "latest"
cmctl = "latest"
envsubst = "latest"
