apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-now
  namespace: database
spec:
  cluster:
    name: postgres16
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
