# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder-chrome
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      chrome:
        annotations:
          reloader.stakater.com/auto: 'true'
        strategy: Recreate
        containers:
          app:
            args:
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 600Mi
    service:
      app:
        controller: chrome
        ports:
          chrome:
            port: 9222
            targetPort: 9222
