---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hoarder-chrome
spec:
  interval: 30m
  maxHistory: 3
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      chrome:
        annotations:
          reloader.stakater.com/auto: 'true'
        strategy: Recreate
        containers:
          app:
            args:
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 600Mi
    service:
      app:
        controller: chrome
        ports:
          chrome:
            port: 9222
            targetPort: 9222
