---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghost
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ghost-secret
    template:
      data:
        database__connection__password: "{{ .GHOST_DB_PASSWORD }}"
        mariadb-root-password: "{{ .GHOST_DB_ROOT_PASSWORD }}"
        mariadb-password: "{{ .GHOST_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: Ghost
      rewrite:
        - regexp:
            source: "(.*)"
            target: "GHOST_$1"
