---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onlyoffice
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onlyoffice-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_TYPE: postgres
        DB_HOST: &dbHost postgres16-rw.database.svc
        DB_PORT: "5432"
        DB_NAME: &dbName onlyoffice
        DB_USER: &dbUser "{{ .ONLYOFFICE_DATABASE_USER }}"
        DB_PWD: &dbPass "{{ .ONLYOFFICE_DATABASE_PASS }}"
        JWT_SECRET: "{{ .ONLYOFFICE_JWT_SECRET }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .CNPG_password }}'
  dataFrom:
    - extract:
        key: OnlyOffice
      rewrite:
        - regexp:
            source: "(.*)"
            target: "ONLYOFFICE_$1"
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
