---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onlyoffice
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: rabbitmq
  values:
    controllers:
      onlyoffice:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6.0@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom: &env
              - secretRef:
                  name: onlyoffice-secret
        containers:
          onlyoffice:
            image:
              repository: docker.io/onlyoffice/documentserver
              tag: 9.0.4
            env:
              WOPI_ENABLED: true
              USE_UNAUTHORIZED_STORAGE: true
              AMQP_URI: amqp://guest:guest@rabbitmq
            envFrom: *env
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
    service:
      app:
        ports:
          http:
            port: 80
    persistence:
      data:
        existingClaim: onlyoffice
        globalMounts:
          - path: /var/www/onlyoffice/Data/certs
          - path: /var/www/onlyoffice/Data
          - path: /var/log/onlyoffice
          - path: /var/lib/onlyoffice/documentserver/App_Data/cache/files
          - path: /var/www/onlyoffice/documentserver-example/public/files
          - path: /usr/share/fonts
    route:
      app:
        hostnames:
          - onlyoffice.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
