---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 30m
  maxHistory: 3
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: 'true'
        strategy: Recreate
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6.0@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom: &env
              - secretRef:
                  name: mealie-secret
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.1.1@sha256:c15f70d7f301145ffa49c988db33071a4585fabf214c2da08bc2cd62737043c8
            env:
              BASE_URL: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
              DB_ENGINE: postgres
            envFrom: *env
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 1Gi
              limits:
                memory: 1Gi
    service:
      app:
        controller: mealie
        ports:
          http:
            port: &port 9000
    route:
      app:
        hostnames: [*host]
        parentRefs:
          - name: envoy-internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
