---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: immich-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        DB_HOSTNAME: '{{ index . "pgbouncer-host" }}'
        DB_PORT: '{{ index . "pgbouncer-port" }}'
        DB_USERNAME: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
        DB_DATABASE_NAME: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-immich
