---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./nfs-pvc.yaml
  - ./configmap.yaml
  - ./redis
  - ./server
  - ./machine-learning
  - ../../../../templates/gatus/external/
