---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trmnl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: trmnl-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: trmnl
        INIT_POSTGRES_HOST: postgres-lb.database.svc
        INIT_POSTGRES_USER: "{{ .DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_password }}"
        DATABASE_URL: "postgresql://{{ .DATABASE_USER }}:{{ .DATABASE_PASSWORD }}@postgres-lb.database.svc:5432/trmnl?sslmode=disable"
        KEYVALUE_URL: "redis://trmnl-dragonfly:6379/0"
        APP_SECRET: "{{ .APP_SECRET }}"
  dataFrom:
    - extract:
        key: trmnl
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
