---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1/job-batch-v1.json
apiVersion: batch/v1
kind: Job
metadata:
  name: ${job}
  namespace: ${ns}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: main
          image: docker.io/restic/restic:0.16.4
          args: ["snapshots", "--cacert", "/cert/ca.crt"]
          envFrom:
            - secretRef:
                name: ${app}-volsync-secret
          resources: {}
          volumeMounts:
            - mountPath: /cert
              name: certificate
      volumes:
        - name: certificate
          secret:
            secretName: ${app}-volsync-secret
            items:
              - key: ca.crt
                path: ca.crt
