---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-mariadb
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb
      version: 20.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 11.7.2-debian-12-r0
    auth:
      existingSecret: ghost-secret
      username: ghost
      database: ghost
    primary:
      persistence:
        existingClaim: ghost-mariadb
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 512Mi
