---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_USER: "{{ .NEXTCLOUD_username }}"
        ADMIN_PASS: "{{ .NEXTCLOUD_password }}"
        OIDC_CLIENT_ID: "{{ .NEXTCLOUD_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .NEXTCLOUD_CLIENT_SECRET }}"
        POSTGRES_DB: &dbName nextcloud
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc
        POSTGRES_USER: &dbUser "{{ .NEXTCLOUD_DATABASE_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .NEXTCLOUD_DATABASE_PASS }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .CNPG_password }}'
        SMTP_HOST: '{{ .SMTP_HOST }}'
        SMTP_USERNAME: "{{ .SMTP_username }}"
        SMTP_PASSWORD: "{{ .SMTP_password }}"
        TOKEN: '{{ .NEXTCLOUD_TOKEN }}'
        S3_ACCESS_KEY: "{{ .ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .SECRET_KEY }}"
  dataFrom:
    - extract:
        key: SMTP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SMTP_$1"
    - extract:
        key: Nextcloud
      rewrite:
        - regexp:
            source: "(.*)"
            target: "NEXTCLOUD_$1"
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
    - extract:
        key: S3
