---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    template:
      data:
        # App
        nextcloud-username: "{{ .username }}"
        nextcloud-password: "{{ .password }}"
        smtp-username: "{{ .SMTP_username }}"
        smtp-password: "{{ .SMTP_password }}"
        smtp-host: "{{ .SMTP_HOST }}:{{.SMTP_PORT}}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: nextcloud
        INIT_POSTGRES_HOST: postgres16-rw.database.svc
        INIT_POSTGRES_USER: "{{ .DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_password }}"
  dataFrom:
    - extract:
        key: Nextcloud
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
    - extract:
        key: SMTP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SMTP_$1"
