---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  timeout: 15m
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nextcloud
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      flavor: fpm
    nginx:
      enabled: true
    imaginary:
      enabled: true
    cronjob:
      enabled: true
      curlInsecure: true
    nextcloud:
      extraVolumes:
        - name: nfs-media
          persistentVolumeClaim:
            claimName: nextcloud-media-nfs
      extraVolumeMounts:
        - name: nfs-media
          mountPath: /nfs/media
      extraInitContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18@sha256:b6d3af974df781c673d37e49bdddfa14a6f5be28b18d2cb7713f0449bea4057b
          envFrom:
            - secretRef:
                name: &secret nextcloud-secret
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: nextcloud-dragonfly.default.svc
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: NEXTCLOUD_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: *secret
              key: NEXTCLOUD_OAUTH_CLIENT_ID
        - name: NEXTCLOUD_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: *secret
              key: NEXTCLOUD_OAUTH_CLIENT_SECRET
      existingSecret:
        enabled: true
        secretName: *secret
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      host: &host cloud.${SECRET_DOMAIN}
      defaultConfigs:
        imaginary.config.php: true
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.43.0.0/16',
              1 => '10.0.0.0/16',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          ); ?>
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'PL',
            'maintenance_window_start' => 2,
          ); ?>
        oidc.config.php: |-
          <?php
          $CONFIG = array (
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_provider_url' => 'https://auth.${SECRET_DOMAIN}',
            'oidc_login_client_id' => getenv('NEXTCLOUD_OAUTH_CLIENT_ID'),
            'oidc_login_client_secret' => getenv('NEXTCLOUD_OAUTH_CLIENT_SECRET'),
            'oidc_login_auto_redirect' => false,
            'oidc_login_end_session_redirect' => false,
            'oidc_login_button_text' => 'Log in with Authelia',
            'oidc_login_hide_password_form' => false,
            'oidc_login_use_id_token' => false,
            'oidc_login_attributes' => array (
                'id' => 'preferred_username',
                'name' => 'name',
                'mail' => 'email',
                'groups' => 'groups',
                'is_admin' => 'is_nextcloud_admin',
            ),
            'oidc_login_default_group' => 'oidc',
            'oidc_login_use_external_storage' => false,
            'oidc_login_scope' => 'openid profile email groups nextcloud_userinfo',
            'oidc_login_proxy_ldap' => false,
            'oidc_login_disable_registration' => true,
            'oidc_login_redir_fallback' => false,
            'oidc_login_tls_verify' => true,
            'oidc_create_groups' => false,
            'oidc_login_webdav_enabled' => false,
            'oidc_login_password_authentication' => false,
            'oidc_login_public_key_caching_time' => 86400,
            'oidc_login_min_time_between_jwks_requests' => 10,
            'oidc_login_well_known_caching_time' => 86400,
            'oidc_login_update_avatar' => false,
            'oidc_login_code_challenge_method' => 'S256'
          ); ?>
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres-lb.database.svc.cluster.local.
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: *secret
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS
    ingress:
      enabled: false
    persistence:
      enabled: true
      existingClaim: *app
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-nfs
        accessMode: ReadWriteMany
    # this seems to be required for nextcloud initialization which takes a long time
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
