---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
spec:
  hostnames:
  - cloud.${SECRET_DOMAIN}
  parentRefs:
  - name: external
    namespace: kube-system
    sectionName: https
  rules:
  - backendRefs:
    - kind: Service
      name: nextcloud
      port: 8080
    matches:
    - path:
        type: PathPrefix
        value: /
