---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: crunchy-pgo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://registry.developers.crunchydata.com/crunchydata/pgo
  ref:
    tag: 5.8.2
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crunchy-postgres-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: crunchy-pgo
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    install:
      clusterLabels:
        app.kubernetes.io/name: pgo
