# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9IMqknkX+BBt/oG/LWL/2y10wzUum50AH4EiV9VeQjHkt2cN8uU6TQ==,iv:t9NDqu2/w7wMswRk31AGqDGQo3TKI/rBlPBPiJm6hvo=,tag:MxtUhJW9bG52yLjLplCwiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRkNlZUZrR09nN2diYnBR
        djFRTDdHajJUTURjVW0yOTdLcHZRUGozN1RzClppejYyNlQweDBROWpDUFlwR2FV
        RHcvMSs0UHhqWUxmTzJ0bHBWOWdHajAKLS0tIG8wT2U1Wld0Mml5V0Z6SXBVTVk0
        QmxjbE5IbmtuMFNoY1l2N2dDUWtISUkK5OSKLY371b9CAa+s4Y+cvVlkfx17TTXb
        xRR5+oUmI1Fcr9ku1SdhED5IkQ/zql5vvmW5Fat5piYVwC1wOrFqag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T15:54:08Z"
  mac: ENC[AES256_GCM,data:wUPP8GyRT8XwdZfKU1XX/ed6JRUAnpe5cp9nWBnO/97407ZyuWh9uvoSJnve4WGCXfaSHRKay9zMETj92FqvNppqOWEpfXDXPgw5iWG+JvZCBst7skyknbLlmlIgDrym6F9+iIBSaw9+mx1xJ1cDCQlc6aQdKBh2zSZVK5E23Ps=,iv:7yR/0vtXo78uu9Po6oDTi5jIvgJCsaCzzMkBXDVWcNo=,tag:X72RES9IdHJfMRHeUmUI/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
