- Infrastructure:
    # - Proxmox:
    #     icon: proxmox.png
    #     href: https://ares.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}:8006
    # - KVM:
    #     icon: pikvm.png
    #     href: https://pikvm.{{HOMEPAGE_VAR_SECRET_TECH_DOMAIN_NAME}}
    # - AdGuard Home:
    #     href: https://adguard.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
    #     widget:
    #       type: adguard
    #       url: https://adguard.{{HOMEPAGE_VAR_SECRET_DOMAIN_NAME}}
    #       username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
    #       password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
    - Cloudflared:
        href: https://dash.cloudflare.com/
        icon: cloudflare-zero-trust.png
        description: Cloudflared Tunnel Status
        widget:
          type: cloudflared
          accountid: "{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}"
          tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}"
          key: "{{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}"
          fields: ["status"]
    - TrueNAS:
        href: "https://{{HOMEPAGE_VAR_NAS_ADDRESS}}"
        icon: truenas.png
        description: Bulk Storage
        widget:
          type: truenas
          url: "http://{{HOMEPAGE_VAR_NAS_ADDRESS}}"
          key: "{{HOMEPAGE_VAR_TRUENAS_API_TOKEN}}"
          enablePools: true
          nasType: core
