# - logo:
#     icon: https://raw.githubusercontent.com/joryirving/home-ops/main/.docs/icons/lds-transparent.png
- search:
    provider: [google]
    focus: false
    target: _blank
- kubernetes:
    cluster:
      cpu: true
      memory: true
      show: true
      showLabel: true
    nodes:
      cpu: true
      memory: true
      show: false
      showLabel: true
# - openmeteo:
#     label: Home
#     latitude: {{HOMEPAGE_VAR_LATITUDE}}
#     longitude: {{HOMEPAGE_VAR_LONGITUDE}}
#     units: metric
#     cache: 5
- datetime:
    text_size: l
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23
