---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: komf-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        KOMF_KOMGA_USER: "{{ .username }}"
        KOMF_KOMGA_PASSWORD: "{{ .password }}"
        application.yml: |
          komga:
            eventListener:
              enabled: true # if disabled will not connect to komga and won't pick up newly added entries
              libraries: [ ]  # listen to all events if empty
            notifications:
              libraries: [ ]  # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
            metadataUpdate:
              default:
                updateModes: [ API ] # can use multiple options at once. available options are API, COMIC_INFO
                aggregate: true # if enabled will search and aggregate metadata from all configured providers
                mergeTags: true # if true and aggregate is enabled will merge tags from all providers
                mergeGenres: true # if true and aggregate is enabled will merge genres from all providers
                bookCovers: true # update book thumbnails
                seriesCovers: true # update series thumbnails
                postProcessing:
                  seriesTitle: true # update series title
                  seriesTitleLanguage: "en" # series title update language
                  alternativeSeriesTitles: false # use other title types as alternative title option
                  alternativeSeriesTitleLanguages: # alternative title languages
                    - "en"
                    - "ja"
                    - "ja-ro"
                  orderBooks: true # will order books using parsed volume or chapter number
                  scoreTag: true # adds score tag of format "score: 8" only uses integer part of rating. Can be used in search using query: tag:"score: 8" in komga
                  readingDirectionValue: # override reading direction for all series. should be one of these: LEFT_TO_RIGHT, RIGHT_TO_LEFT, VERTICAL, WEBTOON
                  languageValue: # set default language for series. Must use BCP 47 format e.g. "en"

          database:
            file: ./database.sqlite # database file location.

          metadataProviders:
            malClientId: "{{ .MAL_CLIENT_SECRET }}" # required for mal provider. See https://myanimelist.net/forum/?topicid=1973077
            defaultProviders:
              mangaUpdates:
                priority: 10
                enabled: true
                mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
                authorRoles: [ "WRITER" ] # roles that will be mapped to author role
                artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ] # roles that will be mapped to artist role
              mal:
                priority: 20
                enabled: true
                mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
              nautiljon:
                priority: 30
                enabled: false
              aniList:
                priority: 40
                enabled: false
                mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
                tagsScoreThreshold: 60 # tags with this score or higher will be included
                tagsSizeLimit: 15 # amount of tags that will be included
              yenPress:
                priority: 50
                enabled: false
                mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
              kodansha:
                priority: 60
                enabled: false
              viz:
                priority: 70
                enabled: false
              bookWalker:
                priority: 80
                enabled: false
                mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
              mangaDex:
                priority: 90
                enabled: false
  dataFrom:
    - extract:
        key: Komf
    - extract:
        key: Komga
