---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name grafana-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GRAFANA_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_CLIENT_SECRET }}"
        # Admin User
        adminUser: "{{ .GRAFANA_username }}"
        adminPass: "{{ .GRAFANA_password }}"
        GF_DATABASE_USER: '{{ .user }}'
        GF_DATABASE_PASSWORD: '{{ .password }}'
        GF_DATABASE_HOST: '{{ index . "pgbouncer-host" }}'
        GF_DATABASE_NAME: '{{ .dbname }}'
        GF_DATABASE_SSL_MODE: 'require'
        GF_DATABASE_TYPE: postgres
  dataFrom:
  - extract:
      key: Grafana
    rewrite:
      - regexp:
          source: "(.*)"
          target: "GRAFANA_$1"
  - extract:
      key: postgres-pguser-grafana
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: crunchy-pgo-secrets
