---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5
  values:
    fullnameOverride: *app
    provider:
      name: rfc2136
    policy: sync
    env:
      - name: "EXTERNAL_DNS_RFC2136_TSIG_SECRET"
        valueFrom:
          secretKeyRef:
            name: &secret rfc2136-secret
            key: rfc2136-tsig-secret
      - name: "EXTERNAL_DNS_RFC2136_TSIG_KEYNAME"
        valueFrom:
          secretKeyRef:
            name: *secret
            key: rfc2136-tsig-keyname
    extraArgs:
      - --rfc2136-host=10.0.0.1
      - --rfc2136-port=53
      - --rfc2136-zone="${SECRET_DOMAIN}"
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-axfr
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=internal
    triggerLoopOnEvent: true
    sources: ["crd", "gateway-httproute", "ingress"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
