apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:zTQ8Hmc9XQ==,iv:ybGnl3fdaUqGMjfBeuwHxCNkCFdA5tP6dAGtOafRzQU=,tag:OVMOztSHKOcCsv5T/aaxdw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEFhYU41WFor
        QXVBNXZsdkFQT2Z4MDhOR3UzTzdDczUybGZjQ2JWdEdKYm90Z2hpRzBBdyt6YTRv
        WXVoM3J5WlJ3cDNMVTJkM0JNcWE5Q2xjU0h4Z0FqeDNXeHZiaHlpVFlWUmpxYnJl
        WklzMkhXeHlQQzlZdEg1ZDBWeHQxR0JxZ1E0TmVVN1lSc2xyWjdOTzQxNGFuUDRo
        L3A1ankvanBVcndNeXhkdXZCUFhpcklPVDZjaHVUKzZyL2ppSHE5NmE4bERCd3lN
        Z2pVRlF0c21YSHVVeUNIeUI1Z25vR0hvMmttTUhWQ1MyNjFiYVoxNlVNdFhVb3Fk
        K0JEMk5zVmYzVGNUSzNKbVh0RmU1ZkZrL29lbGo1OUlLVWNlQlREYnFuR0dEOFRx
        NG83RkNCUmdXaWpvdFYwOEhWako1SDlxM2RaVnQwQWxZQVVwcUR6TzlRY0V2aVo2
        eWVLY3dGdXpzdCtQMXdGV3J2dzdxUzFkRVR3RmlkMXhnOFhFd0xOc2VVTjlPUVFZ
        ak9qbVkxVm1NSVlMY2RnRXZRNFhsOERZcld2eVl6WTNyQXdkanFXQ1hVbmtqWHN2
        bDNCQlFidUNQUDgwRm5FTzZ4ZnMway9TamtJcWZjN21haEVUbDZPa1NRaTVxd2M3
        TFZKK2h3WFZVRmRISVVvZit2d2M1dTFaeWVEYnVUd0JEZEJiaG5KeklTRWdCazUz
        R21Ka2F1blNPWUZBUy9qbkdEUG80QXA0OVFuVnNtMW9oekJDbk9SUkdmZXBUYk0x
        clNEbHZiZVRMTHpEbTFxS3ZWbUM0UWN3UVhXc0UyUXQ2Q01pZXM0MVhBUlRiSnha
        M1Qxa0J5bkZ6TjE4eUVER05maDBzeEZmQkR2d0xua1NnVmhtcThZL0s5N1loSTFx
        a0FmUVVoWGQ2MnpBMVpxbVFiaDhyc3NuaUtoUFN5NHVacUZZTGVrYXJSSGJnZ3hK
        bjM2V3ZtYWdVYXJqN3pYeXJqelNSa21sbHpudjZOREFKc0NoUWZoMHRGT2N6T2k1
        bjIxRVQyeS9MZTl5TDFLSGZoS2pSdGd2Z2c1bVU3cjB5b2gxWkVQV21KeW8xTzVJ
        N1NFRlMyNmFIWnptSGN5b1h1akw2Rm1MSEdKUmh0MHJhdnBFWlpFVW9yTE5vaW9z
        RnRLQXczSHYvYlhaemRQRi82OVJmVGh0eS9FYnk1TmQzZ2VvUTVQMFMyaWtVTkxU
        ZXVXZ2piN08zc3VPSTJIakZ1SE0ycWhlVGxFN0ZNeXhZZTNoYWQzVUd4aDB3WTZw
        UVFzYTlzT20wRlc2dXF5VGkxUUdiUTFkV0Fjb1BvTE1ENEV4eWRPWjZ0N1k2RW4w
        eU1WT1gwOS8rYURkQnF3L0NRMkJTTHNIWjNzMkhUTUVjUTRJV3Q0RjVLNzZqTEI5
        aU9WYTgvZXpGendZT05LWU1lRWtkSnVtcjJyUDUzVnQxVS8xYUg5ME5JdC9UMjVF
        TmdYT3Z6Q1M4K3h3ZkV4a3I1WUliUHVyNlNoeTVLelp5T1B6UGwxdUZoSEkwUU9D
        MlpBV3NuVmpmZnJsRXFwRlQyMUtpMXdqUHZnMzUvRkkwWmNnUFBWYXk4WjladXNs
        YWYxR0pidDdqOStqVHp5RlpVRG1VT1BPQStEcWZOekN2eiticG11OFFKaS9RU3ZE
        cnZ5aGFvRnY4ckpYUFhUdCtZVFdNUEx3N3lRUkRDSEhUVkVoQ2NHcFZ0c1VhWHJz
        SzZMMWlvQ0VNQTl1ckxONzMzR3lPVVBGMmdIbmQxTk9kNWdDVk82aGorMnFHZUho
        L2F1V1dSOXY5ZCtrQ3lra0VieXBBeHp6Vjh6bFlJOFBLekUrSFI3c0x2aE5kZUJq
        NW9HRWVaVXh3OTl5aHc3VVpRVVlsNElGWU1mSXUrUC84UXFTbkVVbmd6STlKa0xr
        ZmZPZ2t3bXk1U3NSSzU1cmZpT0h5cWp6RHdMTGkzb3ZseUFJdFozY2loWThRUQpY
        MWhUMHh1QmJXN21odE9LV2FkL1NHM3ZMbVB6eW8zSkVJZ3A4SHpGWmF3Ci0tLSBI
        R2pyV0R5YXN2RlhyQ1ZDTWhJNWRWQU1QdzFESUlGN2RvRGpoVEczMERZCp4fs7eP
        VBzdDi8Yb8BBCOT5CYlOhzW1h3xntkY2+GkibrgUD9ZFM0hume6P0kyd5gyPw/NH
        u1YciXeVQLJk5GE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq18n284rlerlj59pzvqs6ryef74tfqzv82eazywafrh2rwmkvfr8yj7wenkulmjgmhssy363jm47437ycsjr06kmqdcmru34junh78a4luzzflk30l639zyyutew9gtgwxn2pz5kvd22202sqqnkzs8w6ceh27ssvpjq4dfx2xguqskad29n6zchls7faxk2eqr9amclx2s4ll2cwu4gy265w842m8h8u8vzqcj289aq7gahpgxhnqxkgxhcu303dtfgf3kzn8xtpqxdsytn3avna77z77sjnt2sjupqvpd4d6v9j9xvwm7cjdwr55ey440ldg5k6pc6ddyqpecexqwz6jyuadr8deyy2r82a2kgy24eaxt6y4w27a7v05kcq0lyrevjwyhw8zs0ad7tp7kaa5603kgkdkdqy3zuf9gp9djscda2qx798e0thfc5ttkv6y7cnuals25hn856kxx4ravvs5h47pdxs6kmzzzg7hdd8ngtzaz22md44sltwygr08g4rklgy3ndgzqfjzh0tpv6cahtt32a63cz7znxdq56u5rtadtr6yhgf3gca9prm9khdf49kn3w4fgeu36533k6pvygj8k0g9x0xgykag5yuutk224gute0czcmfxgcrvg0puuv258zkhked30fu8mzpa6qutqjk9cmvtkjd0jlf4g9ae0lym9nym56jnrex4vs2gmzravyrwshph4r42slq3ddraghxvz62380sqsvmcg7r6vxnxlsvtqadqv35pk6g588prgs9vk948x8yx0caczvlc9tvns36ucfzpe2fftnzf50g8j0zxfthm9symsxkw7hczrw0n2ayteqamxzhrvdek8jwy00chs03w50evewq5eups9awgdle3ssmlrfjjuhxxhg26kwyvptnnqlp4hxh9ms5j0kkgjd3vyfrkqu7ukqjnwpae5xetdysgzquqypljvgchwufmgpeeml5uzdl2y7n8yengzvkg4k57j4ry2f6c9908njqepfm2txarlyp9qv76xm8wdwxqtsnl559v5tpr8ghj9md6k2rdhxdq3xskpmd4d4kevkdqdgnxzdsa62yfuv4z8uspjrjlq060vx4lq9qy2yk9v8g950afgw6kx23yzvsnc23zmd06wg8khdvk8d48wapkuzdvvhegy674pvdzyat5945hcddfd0kgtj8gcnmhrtrgtj3nsfephev630mjkplyw7zma7ca5q4mu7x8wra3v4ppc35utkrcsvyc7kkts48qwg3jhnzxthza4p9kf0h5g4dnzy7y098svknczqv3w8uf4hz7gzsrj44tax5qdc2shk83z67ecu5xweqskgvyklsjsak6d0lr3sf9g5ut4ga04wgn9ukxgqed4pmyapgrjm9zux9elxytfmnsyxfujwe60kepuan3m7j3s4hzwl93rvd8m22t8n6qmetzcu3h02xg67j5kvejfqjgv9mvgxt2xtamr9008664pgx2k2eqyhhuhgjgswdv0xjw8yxxan882xlgcwgcr25fs3amk5v86re5vnfkx37p0fjg89c529sujj8p950527l00ycl0l93esshtgqpx969e23x0pk7hdywptnq4g42jwxy0zmzvtqaz3pyxxm8dv44q9z6ye533sjpsy4fdd6vezr5p5w4zj3z7qzvnyfv6grhtfr25uwxgptr73uwjy38esurczfx8qhus60qljvdnu9lrfn6x82vjdd33vu3u5nnhsj30xf9pjt4wqaczps8fzax6kppzd5qf82geg82h287wnz8g9fxcre9l8tm3uk42g974pspmg0sg7zwg5awtw7kstkjfcjlgqz3qsg24x6w4v305raudhj82f506r7dqesttc59hxazzqnmahh602qanpuhkz25jq0t2jdw0ljtyvz404wv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T16:14:11Z"
  mac: ENC[AES256_GCM,data:AuFkV+M1WhDBgYlarz9j3V+i3UhiFsZ9mhyWqxKXaQVu/GEsEuCOcqYjx/QLEq5DDz0JfzM0ecGy4pAVfgAhRlwe4m12FQ8VZbYT2DGRVeG1KrC3Hh0oGSTikij/hf3336grOtSLRcZfmCp7uEwtoby4B1q7ZdEuv/ZEo+TJQYM=,iv:IftowR/y+0ARViIA6tTBqc9PxcU+7879V9RuyWEpKII=,tag:A/desbncTrF8KpDECRwSYg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
