---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: ${NAS_UID}
            runAsGroup: ${NAS_GID}
            runAsNonRoot: true
            fsGroup: ${NAS_GID}
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.3.0
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true
        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.3.0
            env:
              OCIS_INSECURE: false
              DEMO_USERS: false
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: https://files.${SECRET_DOMAIN}
              PROXY_TLS: false
              OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
              STORAGE_USERS_OCIS_ROOT: &storagePath /data
              MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
              NATS_NATS_HOST: 0.0.0.0
              NATS_NATS_PORT: 9233
              ONLYOFFICE_DOMAIN: onlyoffice.${SECRET_DOMAIN}
              GATEWAY_GRPC_ADDR: 0.0.0.0:9142
              PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
              PROXY_ENABLE_BASIC_AUTH: true
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: 9200
          reva:
            port: 9142
          nats:
            port: 9233
    persistence:
      config:
        type: configMap
        name: ocis
        globalMounts:
          - path: /etc/ocis/web.yaml
            subPath: web.yaml
            readOnly: true
      csp:
        type: configMap
        name: ocis-csp
        globalMounts:
          - path: /etc/ocis/csp.yaml
            subPath: csp.yaml
            readOnly: true
      storage-users:
        type: nfs
        server: &nfsServer "${NAS_ADDRESS}"
        path: &nfsPath "${NAS_BASE_URL}/media/software/applications/owncloud"
        globalMounts:
          - path: *storagePath
            subPath: storage-users
      data:
        type: nfs
        server: *nfsServer
        path: *nfsPath
        globalMounts:
          - path: /var/lib/ocis
            subPath: data
          - path: /etc/ocis
            subPath: config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
    route:
      app:
        hostnames:
          - files.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
