---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    template:
      data:
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "uid={{ .LLDAP_READONLY_ADMIN_USERNAME }},ou=people,DC=zed,DC=gay"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LLDAP_READONLY_ADMIN_PASSWORD }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: '{{ index . "jwks.pem" }}'
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_DATABASE: "{{ .dbname }}"
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: '{{ index . "host" }}'
        AUTHELIA_STORAGE_POSTGRES_USERNAME: '{{ index . "user" }}'
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: '{{ index . "password" }}'
        AUTHELIA_NOTIFIER_SMTP_ADDRESS: 'smtp://{{ .SMTP_HOST }}:{{ .SMTP_PORT }}'
        AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .SMTP_username }}"
        AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .SMTP_password }}"
        MEALIE_CLIENT_ID: "{{ .MEALIE_CLIENT_ID }}"
        MEALIE_CLIENT_SECRET_DIGEST: "{{ .MEALIE_CLIENT_SECRET_DIGEST }}"
        HOARDER_CLIENT_ID: "{{ .HOARDER_CLIENT_ID }}"
        HOARDER_CLIENT_SECRET_DIGEST: "{{ .HOARDER_CLIENT_SECRET_DIGEST }}"
        KOMGA_CLIENT_ID: "{{ .KOMGA_CLIENT_ID }}"
        KOMGA_CLIENT_SECRET_DIGEST: "{{ .KOMGA_CLIENT_SECRET_DIGEST }}"
        GRAFANA_CLIENT_ID: "{{ .GRAFANA_CLIENT_ID }}"
        GRAFANA_CLIENT_SECRET_DIGEST: "{{ .GRAFANA_CLIENT_SECRET_DIGEST }}"
  dataFrom:
    - extract:
        key: Authelia
      rewrite:
        - regexp:
            source: "(.*)"
            target: "AUTHELIA_$1"
    - extract:
        key: Authelia JWKS
    - extract:
        key: SMTP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SMTP_$1"
    - extract:
        key: LLDAP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "LLDAP_$1"
    - extract:
        key: Mealie
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MEALIE_$1"
    - extract:
        key: Hoarder
      rewrite:
        - regexp:
            source: "(.*)"
            target: "HOARDER_$1"
    - extract:
        key: Komga
      rewrite:
        - regexp:
            source: "(.*)"
            target: "KOMGA_$1"
    - extract:
        key: Grafana
      rewrite:
        - regexp:
            source: "(.*)"
            target: "GRAFANA_$1"
    - extract:
        key: postgres-pguser-authelia
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
