apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:bRTgimeq8x0+SBsHiNi9+nsztKg7srYgU8OQXie5WCc=,iv:Y12FIaYwEbwGFhI2uZazxIEgZrEBcNRC56RTxNQ4dmI=,tag:iqAFk+U+XBrHX0xrIOpipQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhZa2d5ZHQv
        bjdCcDNoYW81dHNZNmlRVGFHeTNPU1NZUTZ2bVpSK1gzQTBqamRKYlhablRXTnBN
        MUZkeThLdHZqbkNYYWJtRWtvS090RVU5NUZWYkZxTENHbHhjbi9YRURBUHdncTBs
        Qkl2SUU2SkJCZkF0ZWovck9hM3FYYTRhbkt2Wm5Eamo5b3p6ZGd5cUFmRW1kTzc5
        SWl4VkhGeWlMN2VES1NYS3NkMU9SQ1B6QjZMNis2SzFEOFlRSThrVURLbm5aSE56
        RC9Qa1ZMQ3ZmbjNFNHlaNDNEd3RNZWJqZDJiNUc5RUhGSmpNN0hnMEphbHI0Y2d5
        VEREb0owdG1kN1VYeTlaRjhMY24xaFZlNkpPa2FaTjNPUEo5NlBydlQ1S1JWWEJM
        SGtWbUxaTitlSE1jVW4ybGpBZk5JUEtyRXZSa1JYalJBcnFYZjZSLzlQV24xd1hw
        RzVwNlpYVGJKU1VCRG1TeUVPZ3NGOHlVVUU4cmFwRjVSR0cwNEZPZmY5bExLV0FK
        d2NqcmpwVS9YY3FMbUtORlBtK2NyeFE0MzExR1NnenhMSTFxVWJYRDF4V0RVZkNV
        VExia25QalU3aVA2QW0zaDFFSHY0NUp6U2FmUitFbThwZEEvNlArSnZoL2FiYS9q
        N25ta1RvaTJ1T0FPaVdLQU5CQnRYVHRjT3hGd2hRNmxLRlA1dFl5UU5GcTErSXd1
        N2RLNVMvNWVlSHk2Mm5KTVlMZk9TVi9hOWRNcTVoM25XTVluYnBPbE9sRFRIcFFS
        Q2RWRkhyeXJsZ3JqeUdKMjNjY2VKazA1bHBxS1N2R1gvMmV0Y0dpUjNnWkkzYTgr
        R25EVkg5YnVxRm5CL0JlWm9NVWZSZFRwY2lZeWJncVdUVlEyV2kvT2RlSm8xUC9I
        bjJnRTl4ODAycHJRaGNVWmtHYUhEd2s5ZXloRWdNUXdheE8vK2lLQ3h0bERPL1oz
        T3g1Tk1IaFdMSzFYb1RsU1RQUFhtSHVZRGRhZDJyL3lHYjJVTjZZQmwxYU14QU5q
        NXhsaUllWkFaZ3h5dDJFMmJRTUF4V1RCL2x1ZmxNRWxhTUdhcEE0WmszQmdjK05a
        bHVpU3o4T3VUZm1kb054Kyt3ZVBROCtCUG5VTzRpTFlIaXhHMVkraDJ4UUJ2RnUz
        Nyt1dUN0L2Rrak96aVdtcnRHSWxoczdJcDRTTHAxQ0hvYXRlRGRScVI5V2lJQzZm
        RmtKWDNEa2FERThTNkMyc2NEOHJwMGtsTjkvYmhzVjk5eERoWk1TTVVBV3NkcXFk
        SFBrdmVvNVlIai8zSkJZYXZMZWtYdzBXZjVzWFpuWFpQMi9WbXZtQVo4aUlwaG9V
        QUZsOFVZRjRvV2JUZVR4SHpOc2pzQTAxWFVaZEkzZ3U5WFQxOGJBL0xxVFo4TjVI
        SWwwRW9zSHUwalo1bGh2UGYxUHFpUURsL1Q4Z05MQWUydmxLK2dpLzVpNkY0alJp
        UG5VYmFyWG5TNFVodkwvWXgyUk5pQmpQTUpFTC9Tb3kyNm03UG9sSVNJN0R4bUMr
        b3FnTVhOSlNVQXUxRGNqNjBJZWxncGRmeWM4OTlMclBWR0lhZ3hUYWtscnEzSWkz
        aEVqOUF6WmY3MzFSUDY5bnZqdm1mVWZOWU1RS29jdzVJWGgrNXgxZmtrV1pNaTBw
        UlFpd2xWYlA2OE5scVQyMENxMUVnV1g1NHoxSHF2RWdUQzZSWlltbGowaEdlMmgy
        QzVoTUF6d2Vwa3RnSnIyUmUwSXlPUWtETDhiaCtXUHhKL1JQOWhKSGFsalAvQnQr
        UFUxUnV6bVBWdEJqT1o2WlhBdXFHSWxSaWVWK3BycWZ0TUtrSkVjV2s1aVBHWFRW
        VWUrUlpiQ0hyajJkbDVTa1FyK0NsNDZRN3gvTUNjSHRPYVlzSnJqQ2wyUEwxc0Rl
        czBPaFhwaTBabXh0a04zOVNNNDdmSlRIbEF1UkszbUlSUk5mSWRvdjdVZW5VZwoy
        UFBIK0N1SVBLbFl2TEVTOEdkeW14QTRpWldTalJEd3poRFhDMFM1eEpzCi0tLSBO
        NVUwL3FoTGYrSVVjd2ozdUYzSHZxT3Znc0pVWDFocHVFZFIxUzBTYlpFCu/1whX2
        MpROtVEYwdSkTqrpvSyGDXaSeEpOj9yYoyBzrfx47rc5EiSfVjE7QRPeTL2lkbEW
        W5kB1u3riJTHIyE=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq18n284rlerlj59pzvqs6ryef74tfqzv82eazywafrh2rwmkvfr8yj7wenkulmjgmhssy363jm47437ycsjr06kmqdcmru34junh78a4luzzflk30l639zyyutew9gtgwxn2pz5kvd22202sqqnkzs8w6ceh27ssvpjq4dfx2xguqskad29n6zchls7faxk2eqr9amclx2s4ll2cwu4gy265w842m8h8u8vzqcj289aq7gahpgxhnqxkgxhcu303dtfgf3kzn8xtpqxdsytn3avna77z77sjnt2sjupqvpd4d6v9j9xvwm7cjdwr55ey440ldg5k6pc6ddyqpecexqwz6jyuadr8deyy2r82a2kgy24eaxt6y4w27a7v05kcq0lyrevjwyhw8zs0ad7tp7kaa5603kgkdkdqy3zuf9gp9djscda2qx798e0thfc5ttkv6y7cnuals25hn856kxx4ravvs5h47pdxs6kmzzzg7hdd8ngtzaz22md44sltwygr08g4rklgy3ndgzqfjzh0tpv6cahtt32a63cz7znxdq56u5rtadtr6yhgf3gca9prm9khdf49kn3w4fgeu36533k6pvygj8k0g9x0xgykag5yuutk224gute0czcmfxgcrvg0puuv258zkhked30fu8mzpa6qutqjk9cmvtkjd0jlf4g9ae0lym9nym56jnrex4vs2gmzravyrwshph4r42slq3ddraghxvz62380sqsvmcg7r6vxnxlsvtqadqv35pk6g588prgs9vk948x8yx0caczvlc9tvns36ucfzpe2fftnzf50g8j0zxfthm9symsxkw7hczrw0n2ayteqamxzhrvdek8jwy00chs03w50evewq5eups9awgdle3ssmlrfjjuhxxhg26kwyvptnnqlp4hxh9ms5j0kkgjd3vyfrkqu7ukqjnwpae5xetdysgzquqypljvgchwufmgpeeml5uzdl2y7n8yengzvkg4k57j4ry2f6c9908njqepfm2txarlyp9qv76xm8wdwxqtsnl559v5tpr8ghj9md6k2rdhxdq3xskpmd4d4kevkdqdgnxzdsa62yfuv4z8uspjrjlq060vx4lq9qy2yk9v8g950afgw6kx23yzvsnc23zmd06wg8khdvk8d48wapkuzdvvhegy674pvdzyat5945hcddfd0kgtj8gcnmhrtrgtj3nsfephev630mjkplyw7zma7ca5q4mu7x8wra3v4ppc35utkrcsvyc7kkts48qwg3jhnzxthza4p9kf0h5g4dnzy7y098svknczqv3w8uf4hz7gzsrj44tax5qdc2shk83z67ecu5xweqskgvyklsjsak6d0lr3sf9g5ut4ga04wgn9ukxgqed4pmyapgrjm9zux9elxytfmnsyxfujwe60kepuan3m7j3s4hzwl93rvd8m22t8n6qmetzcu3h02xg67j5kvejfqjgv9mvgxt2xtamr9008664pgx2k2eqyhhuhgjgswdv0xjw8yxxan882xlgcwgcr25fs3amk5v86re5vnfkx37p0fjg89c529sujj8p950527l00ycl0l93esshtgqpx969e23x0pk7hdywptnq4g42jwxy0zmzvtqaz3pyxxm8dv44q9z6ye533sjpsy4fdd6vezr5p5w4zj3z7qzvnyfv6grhtfr25uwxgptr73uwjy38esurczfx8qhus60qljvdnu9lrfn6x82vjdd33vu3u5nnhsj30xf9pjt4wqaczps8fzax6kppzd5qf82geg82h287wnz8g9fxcre9l8tm3uk42g974pspmg0sg7zwg5awtw7kstkjfcjlgqz3qsg24x6w4v305raudhj82f506r7dqesttc59hxazzqnmahh602qanpuhkz25jq0t2jdw0ljtyvz404wv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T16:14:11Z"
  mac: ENC[AES256_GCM,data:k/Dc48kDy0TLcHeDCJLZ72NJUICXpMdTDIDTsPBh0TDiTPZSeSNFKrFVEGOQY2Tv8ZWdycELo8JwwnwBrLi6FRdT/fLIF1LsXpJBh35lS+7m6hv70nffTchbZPh0mH5NWJonHG56pkXf4uGSWxGSuvamaUybnPe4lU7ruJEoUUo=,iv:WVU4bzTbp25pKxLtZJC3JcG+G4RWmzoDKD7kSEBu88o=,tag:kWotGvJWmn1tPj3IZ1PP3g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
