---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mariadb
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/mariadb
  ref:
    tag: 22.0.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-mariadb
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: mariadb
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: 11.7.2-debian-12-r0
    auth:
      existingSecret: ghost-secret
      username: ghost
      database: ghost
    primary:
      persistence:
        existingClaim: ghost-mariadb
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 512Mi
