---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grimmory-secret
    creationPolicy: Owner
    template:
      data:
        MARIADB_PASSWORD: &dbpass "{{ .GRIMMORY_MARIADB_PASSWORD }}"
        DATABASE_PASSWORD: *dbpass
        MARIADB_ROOT_PASSWORD: "{{ .GRIMMORY_MARIADB_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: Grimmory
      rewrite:
        - regexp:
            source: "(.*)"
            target: "GRIMMORY_$1"
