---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app grimmory
  namespace: media
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  dependsOn: []
  interval: 1h

  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      grimmory:
        labels:
          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          mariadb:
            image:
              repository: docker.io/library/mariadb
              tag: 12.3.2-noble
            env:
              MARIADB_DATABASE: grimmory
              MARIADB_USER: grimmory
              PGID: 1000
              PUID: 1000
            envFrom: &envFrom
              - secretRef:
                  name: grimmory-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - bash
                      - -c
                      - |-
                        mariadb-admin ping --socket=/run/mysqld/mysqld.sock --user=root --password=$${MARIADB_ROOT_PASSWORD}
            restartPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              seccompProfile: { type: Unconfined }
          wait-for-mariadb:
            image:
              repository: docker.io/wait4x/wait4x
              tag: 3.6.0
            args:
              - "mysql"
              - "grimmory:$(DATABASE_PASSWORD)@tcp(localhost:3306)/grimmory"
            envFrom: *envFrom
        containers:
          app:
            image:
              repository: ghcr.io/grimmory-tools/grimmory
              tag: v3.3.2@sha256:8a3a046822dee460f3e67df5d548e3b9842057a54ed830026edb20ecc116c8ce
            command:
              - java
            args:
              - -jar
              - /app/app.jar
            env:
              DATABASE_URL: jdbc:mariadb://localhost:3306/grimmory
              DATABASE_USERNAME: grimmory
            envFrom: *envFrom
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: &port 6060
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: *port
                  failureThreshold: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 500Mi
              limits:
                memory: 2Gi
        pod:
          labels:
            pod-security.kantai.xyz/allow-seccomp-unconfined: "true"
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: networking
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: grimmory
          gethomepage.dev/description: Ebook Manager
          gethomepage.dev/group: Downloaders
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          grimmory:
            app:
              - path: /app/data
                subPath: app
            mariadb:
              - path: /var/lib/mysql
                subPath: mysql
      mysqld:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Mi
        advancedMounts:
          grimmory:
            mariadb:
              - path: /run/mysqld
      tmpfs:
        type: emptyDir
        advancedMounts:
          grimmory:
            app:
              - path: /tmp
                subPath: app
            mariadb:
              - path: /tmp
                subPath: mysql
      library:
        type: nfs
        server: ${NAS_ADDRESS}
        path: ${NAS_BASE_URL}/media
        advancedMounts:
          grimmory:
            app:
              - path: /library/books
                subPath: books
              - path: /library/bookdrop
                subPath: bookdrop
