---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    creationPolicy: Owner
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .API_KEY }}"
        SONARR__POSTGRES__MAINDB: sonarr_main
        SONARR__POSTGRES__LOGDB: sonarr_log
        SONARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc
        SONARR__POSTGRES__USER: &dbUser "{{ .DATABASE_USER }}"
        SONARR__POSTGRES__PASSWORD: &dbPass "{{ .DATABASE_PASSWORD }}"
        SONARR__POSTGRES__PORT: '5432'
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_SUPER_PASS: '{{ .CNPG_password }}'
  dataFrom:
    - extract:
        key: Sonarr
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
