---
# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/authelia/refs/heads/master/docs/static/schemas/v4.38/json-schema/configuration.json
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
authentication_backend:
  ldap:
    implementation: custom
    start_tls: false
    address: ldap://lldap.security.svc.cluster.local:3890
    timeout: 5s
    base_dn: dc=zed,dc=gay
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
  password_reset:
    disable: true
  refresh_interval: 1m

access_control:
  default_policy: one_factor

identity_providers:
  oidc:
    clients:
      - client_id: $${MEALIE_CLIENT_ID}
        client_name: Mealie
        client_secret: $${MEALIE_CLIENT_SECRET_DIGEST}
        public: false
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
        redirect_uris:
          - "https://mealie.${SECRET_DOMAIN}/login"
          - "https://mealie.${SECRET_DOMAIN}/login?direct=1"
      - client_id: $${HOARDER_CLIENT_ID}
        client_name: Hoarder
        client_secret: $${HOARDER_CLIENT_SECRET_DIGEST}
        public: false
        authorization_policy: one_factor
        consent_mode: implicit
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://hoarder.${SECRET_DOMAIN}/api/auth/callback/custom
        userinfo_signed_response_alg: none
      - client_id: $${KOMGA_CLIENT_ID}
        client_name: 'Komga'
        client_secret: $${KOMGA_CLIENT_SECRET_DIGEST}
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://komga.${SECRET_DOMAIN}/login/oauth2/code/authelia'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        grant_types:
          - 'authorization_code'
        userinfo_signed_response_alg: 'none'
      - client_id: "$${GRAFANA_CLIENT_ID}"
        client_name: 'Grafana'
        client_secret: '$${GRAFANA_CLIENT_SECRET_DIGEST}'
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://grafana.${SECRET_DOMAIN}/login/generic_oauth'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: authelia_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}
  redis:
    database_index: 2
    host: dragonfly.database.svc.cluster.local

notifier:
  disable_startup_check: true
  smtp:
    sender: "Authelia <authelia@${SECRET_DOMAIN}>"
    disable_require_tls: false
