---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lidarr-secret
    creationPolicy: Owner
    template:
      data:
        LIDARR__AUTH__APIKEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: Lidarr
