---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barman-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: barman-cloud-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        tls.crt: '{{ index . "ca.crt" }}'
        tls.key: '{{ index . "ca.key" }}'
  dataFrom:
    - extract:
        key: TrueNAS CA
    - extract:
        key: TrueNAS CA Key
