---
# yaml-language-server: $schema=https://crd.movishell.pl/core/persistentvolume_v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: "${NAS_ADDRESS}"
    path: "${NAS_BASE_URL}/media/software/applications/immich"
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime", "nodiratime"]
---
# yaml-language-server: $schema=https://crd.movishell.pl/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeMode: Filesystem
  volumeName: immich-nfs
