# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:AeQPnq1T5o9T7Bgu0DAxCrfKLM+Ljh/Tv930eXO3kqjjcPfP1yfEtuSGk+0dbmEMQjanynbu6Kh1Z8IgXd5F9IXrcMcMJYZ/nINUTQixQ+ekyvJIABePhzPskOaMKUgFNU0Q/ufb5T6ZizOEE/IuNXdRY622moYBCVBeQKPo2Gnh2HLNtxRJGWrdVUgPBJ1SWRjfr2xDArfyJnIkw1MQBuhDgBWzgc6sak6w4swHtDJWFvgi,iv:anQvbSaiasa5khd4hyVn6Az17U8AmHqb1Vi8P1Rm8q4=,tag:r46+yN4wrUqBLgVqVn3vYA==,type:str]
sops:
  age:
    - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb2d0Y0tJSDhtL0tFVW1I
        L3Azdzh0Nm1pOG1pWVg0WHJBQVVuWFJjSTFNCjA4WVplNUtGa3JOZXVKV3FEVi9p
        REE2Y0puMGMxbzZpR1A1RzNaZTJwVW8KLS0tIEtFYlBCYm5MdHpYbzBjMzZKNk9O
        bmU0OURTQmtZbElRa2xzbnNjR3MyUlEKd5ClTb3vD2Sus/7ElwBY4ocSh4nmFPSw
        9XdhIRV+Mrfe567ix0cOiNF9PFZBpi8kyDlplTpVS5KCWjo17Bl1SA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T13:14:34Z"
  mac: ENC[AES256_GCM,data:vZ9p3Arro0G1QCjnzV5tP/0KxN9R/tYsrMqlX26khDQYPuptvlbbdEMabCJEiIaVkdcisrmndQZIwce/Y/i4BMSov91wBOi0/ZM0MLWOnDtkK6YWrzqKmv3ux9QtalIqIC8xu5SDrvNBpe0I+HruwvBbkCbbf6UnVVy0B4K4+DM=,iv:C0eUMEZ5ly3AWI2YbAdYgS/PXzD+fQrPhpLmqvS9fvM=,tag:McQJiFAuHN6+Vpkkkkv5mg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
