---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      radarr:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.0.3.10276
            env:
              TZ: Europe/Warsaw
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
              RADARR__SERVER__PORT: &port 80
              RADARR__UPDATE__BRANCH: develop
            envFrom:
              - secretRef:
                  name: radarr-secret
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 1024Mi
    service:
      main:
        controller: radarr
        ports:
          http:
            port: *port
    route:
      main:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    defaultPodOptions:
      enableServiceLinks: true
      securityContext:
        runAsUser: ${NAS_UID}
        runAsGroup: ${NAS_GID}
        fsGroup: ${NAS_GID}
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
    persistence:
      config:
        enabled: true
        existingClaim: radarr
      media:
        enabled: true
        type: nfs
        globalMounts:
          - path: /media
        server: "10.0.2.3"
        path: "/mnt/core/media"
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      limits:
        memory: 500Mi
