---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
secretGenerator:
  - name: unbound-certificates
    files:
      # - ca.pem=./certs/unbound_control.pem.enc
      - ca.pem=./certs/ca-certificates.crt.enc
      - client.pem=./certs/unbound_control.pem.enc
      - client.key=./certs/unbound_control.key.enc
generatorOptions:
  disableNameSuffixHash: true
