---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qui-secret
    creationPolicy: Owner
    template:
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
        QUI__OIDC_CLIENT_SECRET: "{{ .QUI_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: qui
      rewrite:
        - regexp:
            source: "(.*)"
            target: "QUI_$1"
