---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: homepage-config
    files:
      - ./config/bookmarks.yaml
      - ./config/docker.yaml
      - ./config/kubernetes.yaml
      - ./config/services.yaml
      - ./config/settings.yaml
      - ./config/widgets.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
  - ../../../../templates/gatus/guarded
