---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 5
  values:
    fullnameOverride: *app
    provider:
      name: pihole
    policy: upsert-only
    env:
      - name: "EXTERNAL_DNS_PIHOLE_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: &secret pihole-secret
            key: password
    extraArgs:
      - --pihole-server=http://10.0.0.1:8080
      - --pihole-tls-skip-verify
      - --pihole-api-version=6
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=internal
    triggerLoopOnEvent: true
    sources: ["crd", "gateway-httproute", "ingress"]
    registry: noop
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
