apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Wyt+5j/fxSCYVMPhrY/WECbrk/tPIavSlWbhHxqWKPT/ST2j7IGldw==,iv:EsNB4mCwtdIjl4KeJdMh2UY2mZPyYq5NCD0yL7eC9sI=,tag:id9hZxkA+Z/15McbwvWZVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHBWcm41dERC
        SXRTZy9xeHFVelZrWkcwTHdOWm9vL0ZPNG1BZndwRnBHWExtVVZrdzBaamE1dDBD
        ZFBUZ2prSUFoZWJaaUxsb0hwN2dEMWJEamRVYnNwY2VZWHpZMGdsMUJLOFd0ZVF4
        SnJrUzlVOTloQ0lyK1BXT0d6Wk0vcWVjWERRWmQ5ak4xQnh2TGFBcjZRSkpLUkhV
        VDZQVzV1WXI1bmh0MnhtWG9yS09oUkVONDVXR2FmWEVaS0hsTFFEMlFVdFBuaEU0
        ejR3RlJTMitGcG5ZYjdzbVlxRUE2Mlh1M2NWTHB4SVNZTTVqZXJSb3VzTVREcno5
        ZUtOVUIwSEIxdlp6OWhaVkxaUFhtNC83TEdaMHQvUmt1QTZISEJlK3NvYzBHV3dK
        c24rNjArb3ZHWGpBazlrRGE1REZTb3J1UENrYlFZVStFRVMwREdMTW96M1N6VGlu
        NXdscDM4dUZYTVdLbVdkWDl3R1dFZ1F6dk5UT2MvcGhoWmtXSFNrdURjaVpPWjEv
        Ly9IMGwrdGNYdEQ5REhhaENmTFF4REl2K0tXc0k2dEpxM1hMZVczT01WbjhxSFVq
        U2NlUEJxR2ZjMWxmUStaZDErNm9PcUk1WGRYajkzTHdXaGhud1p0aFVSSFdyMG9H
        cTFZYzdrbzBVc2VPN0N5ZVN5czc5dlpFNmQ5bTVMUTA4RC9MMEFJa2I0ME51OVJ3
        T01SRXhlREtZWm9GalV1YW9Zci9Eb0lYelc4c1ZSZCtRTlphOE5XKytwb2VwNGZH
        NVVqWmN5WWFqL3FnNkgvcmF6UmkzUCt4bGtzRlI1VjkwdHdYMGx2WHQ0VzcrOTdF
        NFkxSVZQRnQ2UlNDV09hM3RtWGJtL2J1R28zSkwyQURPR3lFUjFQdlI4TjhaVHJS
        WEVMdDBBZVZIbzZ6MnhBTGVRS29MTG41Y0lBZWxmSGx6RS9oMlZNcmREenZCZnFI
        QklqQ3Rpa0NwK1puTVFTYkVVZXVtRi9LRjdZTnVkTS9rNEs5UlNuVm9SN3hFcTA5
        NUJuY29JT1pTRkNmZUNKbCttUzhFa1hjOEt4RWZqL0VZQUhLNVpyUjUyb3JPYW5h
        MTNZa1lnZkRMMmQ3ZUdQWTNkUEVIVTREbEhTdnJzN01uZTE2T0RxZ050ZWNjd2Q1
        VG5tZHloRjUzdEgxdHM0YjNZVThJQ25tNGR1R0ZlaVJrUS9SNUljTGhUU0JiQWJr
        YzQrYVc4QmE4aGd4YUNaTldTVTNPb0xSRVNFM0FXNkRObXBuZjk2cjZkQ0lvWndU
        WWNiaGFXbGZ4d251UHA5bURnNENWZjM1WFRRdEVFS2hMN0pUbEFHKzhJOHloSWZa
        dDZ3c2JFS1B1ckJXTE9OcytJQzZROGJoaWpUQjNZM1BMSjViVitkV0Vmaytadlhn
        UG1HSWhUbU52ZnQxVVMxRGxLcytNWVpGSk9yc0lJOEZ1SlZMTnVKYzJZSTdHUHVz
        cjVpeGI0d21YWnBxSmF4RWdkU2J4V0VZa0d4T3RtSTRJT2NZS0RpbFdCcmk1MG5P
        am1PdHprcERlWVhlQ3ArZU5iZXFxdFhIQmNuYWYvOGJ2dytNZEhQcVlyK2VWSjVZ
        dHFJOVZvZnZ5d0k3SG1tdldBbllmaWsxd3NkM0xGbitWOFVkUEdIVUFNR3QxdlpD
        VElHV2JVZGxxZ0wxRzIwbEtFczJNT1grNHJmUDVxU002UW5hWlVwSncrdnIrZmI2
        Z0VOMlVyVzc2MEZmWG02UTRXOVJPOEFmc2paQ0NEREl1eFY1V0phd0xka1BMRWI0
        a2drWTltV1V4MlptTzZFV3FtVkdGS0tLQ0lFcFdrNitiekNuckNWdFVycDNEU0Vr
        dzZZMWFzOS95cjc3dGFZc1pGSFNzSHZvQnNhelliUm5sVU9mcDJkQ1ZLUWMxTlRX
        VVVQSjRibHpyS3lPRVZZME5LVXZpdFZtZHQ4MWZYM2ZjWDZsYXdsZE9uM2xDQQpy
        QThqVnVYT0c5QmcyeUFhNWdHSW9TcFpaanIxajl1MkVtQ2NkTStKOTJnCi0tLSBE
        WFMvVnRmNVo4U1ErazJoSXU0cXBmMjlYSURwQ3NFVUFEVXJvbHdndmZBCnxdcY95
        AU7k5TFD/viG2k/vMaZ8MKkuvKomRXhwSTLxmyPNkTGSvs1WFvasYA8JTuooM1da
        uhwC+0CjsiMP6aY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq18n284rlerlj59pzvqs6ryef74tfqzv82eazywafrh2rwmkvfr8yj7wenkulmjgmhssy363jm47437ycsjr06kmqdcmru34junh78a4luzzflk30l639zyyutew9gtgwxn2pz5kvd22202sqqnkzs8w6ceh27ssvpjq4dfx2xguqskad29n6zchls7faxk2eqr9amclx2s4ll2cwu4gy265w842m8h8u8vzqcj289aq7gahpgxhnqxkgxhcu303dtfgf3kzn8xtpqxdsytn3avna77z77sjnt2sjupqvpd4d6v9j9xvwm7cjdwr55ey440ldg5k6pc6ddyqpecexqwz6jyuadr8deyy2r82a2kgy24eaxt6y4w27a7v05kcq0lyrevjwyhw8zs0ad7tp7kaa5603kgkdkdqy3zuf9gp9djscda2qx798e0thfc5ttkv6y7cnuals25hn856kxx4ravvs5h47pdxs6kmzzzg7hdd8ngtzaz22md44sltwygr08g4rklgy3ndgzqfjzh0tpv6cahtt32a63cz7znxdq56u5rtadtr6yhgf3gca9prm9khdf49kn3w4fgeu36533k6pvygj8k0g9x0xgykag5yuutk224gute0czcmfxgcrvg0puuv258zkhked30fu8mzpa6qutqjk9cmvtkjd0jlf4g9ae0lym9nym56jnrex4vs2gmzravyrwshph4r42slq3ddraghxvz62380sqsvmcg7r6vxnxlsvtqadqv35pk6g588prgs9vk948x8yx0caczvlc9tvns36ucfzpe2fftnzf50g8j0zxfthm9symsxkw7hczrw0n2ayteqamxzhrvdek8jwy00chs03w50evewq5eups9awgdle3ssmlrfjjuhxxhg26kwyvptnnqlp4hxh9ms5j0kkgjd3vyfrkqu7ukqjnwpae5xetdysgzquqypljvgchwufmgpeeml5uzdl2y7n8yengzvkg4k57j4ry2f6c9908njqepfm2txarlyp9qv76xm8wdwxqtsnl559v5tpr8ghj9md6k2rdhxdq3xskpmd4d4kevkdqdgnxzdsa62yfuv4z8uspjrjlq060vx4lq9qy2yk9v8g950afgw6kx23yzvsnc23zmd06wg8khdvk8d48wapkuzdvvhegy674pvdzyat5945hcddfd0kgtj8gcnmhrtrgtj3nsfephev630mjkplyw7zma7ca5q4mu7x8wra3v4ppc35utkrcsvyc7kkts48qwg3jhnzxthza4p9kf0h5g4dnzy7y098svknczqv3w8uf4hz7gzsrj44tax5qdc2shk83z67ecu5xweqskgvyklsjsak6d0lr3sf9g5ut4ga04wgn9ukxgqed4pmyapgrjm9zux9elxytfmnsyxfujwe60kepuan3m7j3s4hzwl93rvd8m22t8n6qmetzcu3h02xg67j5kvejfqjgv9mvgxt2xtamr9008664pgx2k2eqyhhuhgjgswdv0xjw8yxxan882xlgcwgcr25fs3amk5v86re5vnfkx37p0fjg89c529sujj8p950527l00ycl0l93esshtgqpx969e23x0pk7hdywptnq4g42jwxy0zmzvtqaz3pyxxm8dv44q9z6ye533sjpsy4fdd6vezr5p5w4zj3z7qzvnyfv6grhtfr25uwxgptr73uwjy38esurczfx8qhus60qljvdnu9lrfn6x82vjdd33vu3u5nnhsj30xf9pjt4wqaczps8fzax6kppzd5qf82geg82h287wnz8g9fxcre9l8tm3uk42g974pspmg0sg7zwg5awtw7kstkjfcjlgqz3qsg24x6w4v305raudhj82f506r7dqesttc59hxazzqnmahh602qanpuhkz25jq0t2jdw0ljtyvz404wv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T16:14:11Z"
  mac: ENC[AES256_GCM,data:RsFQxhMfMHIVKLdpcc5u/rxoxRzY/p/9GWzGwShrRT3WhJMorJFtn7RqeVdJjmVioahM/QPliSdVlyBZEFHiWTEaaqLEUxyRBO2G6XxHhsFlmqlH0oR1EvMe070g+9VL8FuI3kUXX6vavznUsqA8/V4QbkBnFSHIN+GmivTQNzA=,iv:rP0mz2ZzgLNIgdqP4JayyzhOcFq8cDrkSiLzEInf33A=,tag:nfc6+hZiFOqY1nEz0lFGSA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
