---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ocis-collab
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: onlyoffice
    - name: ocis
  values:
    controllers:
      ocis-collab:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          ocis-collab:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.2.0
            command: ["ocis", "collaboration", "server"]
            env:
              COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
              COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
              MICRO_REGISTRY: "nats-js-kv"
              MICRO_REGISTRY_ADDRESS: "ocis:9233"
              OCIS_GATEWAY_GRPC_ADDR: "ocis:9142"
              COLLABORATION_LOG_LEVEL: debug
              COLLABORATION_WOPI_SRC: https://wopi.${SECRET_DOMAIN}
              COLLABORATION_APP_NAME: "OnlyOffice"
              COLLABORATION_APP_PRODUCT: "OnlyOffice"
              COLLABORATION_APP_ADDR: https://onlyoffice.${SECRET_DOMAIN}
              COLLABORATION_APP_ICON: https://onlyoffice.${SECRET_DOMAIN}/web-apps/apps/documenteditor/main/resources/img/favicon.ico
              OCIS_URL: https://files.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
    service:
      app:
        ports:
          http:
            port: 9300
          grpc:
            port: 9301
    persistence:
      config:
        type: configMap
        name: ocis
        globalMounts:
          - path: /etc/ocis/web.yaml
            subPath: web.yaml
            readOnly: true
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        rules:
          - backendRefs:
              - name: *app
                port: 9300
        hostnames:
          - wopi.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
