---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis-collaboration
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      collab:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          collab:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.1.2
            command: ["bash", "-c", "ocis collaboration server"]
            env:
              COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
              COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
              MICRO_REGISTRY: "nats-js-kv"
              MICRO_REGISTRY_ADDRESS: "ocis:9233"
              COLLABORATION_WOPI_SRC: https://wopi.${SECRET_DOMAIN}
              COLLABORATION_APP_NAME: "CollaboraOnline"
              COLLABORATION_APP_PRODUCT: "Collabora"
              COLLABORATION_APP_ADDR: https://collabora.${SECRET_DOMAIN}
              COLLABORATION_APP_ICON: https://collabora.${SECRET_DOMAIN}/favicon.ico
              COLLABORATION_APP_INSECURE: "true"
              COLLABORATION_APP_PROOF_DISABLE: "true"
              COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
              COLLABORATION_LOG_LEVEL: info
              OCIS_URL: https://files.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
    service:
      app:
        controller: collab
        ports:
          http:
            port: 9300
          grpc:
            port: 9301

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: wopi.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: ocis
        globalMounts:
          - path: /etc/ocis
            subPath: config
