---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app playwright
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      playwright:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/browserless/chromium
              tag: v2.37.1
            env:
              TZ: ${TIMEZONE}
              DATA_DIR: /config/
              ALLOW_GET: true
              SCREEN_WIDTH: 1920
              SCREEN_HEIGHT: 1080
              SCREEN_DEPTH: 24
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  - SYS_ADMIN
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: &port 3000
    persistence:
      config:
        existingClaim: rsshub-playwright
        globalMounts:
          - path: /config/
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      dev-shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
          - path: /dev/shm
      var-run:
        type: emptyDir
        globalMounts:
          - path: /var/run
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
