---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./flux-podmonitor.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - ./config/flux-resource.yaml
configurations:
  - kustomizeconfig.yaml
