# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.255.254:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.255.254"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none



nodes:
  - hostname: "talos-01"
    ipAddress: "10.0.10.1"
    installDisk: "/dev/sda"
    machineSpec: &spec
      secureboot: false
      mode: nocloud
      bootMethod: disk-image
      imageSuffix: raw.xz
    controlPlane: true
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: "!system_disk"
          minSize: 60GiB
          grow: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:f9:53:56:3e:a8"
        dhcp: false
        addresses:
          - "10.0.10.1/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.255.254"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/i915
            - siderolabs/intel-ice-firmware
            - siderolabs/mei
            - siderolabs/xe
            - siderolabs/intel-ucode
  - hostname: "talos-02"
    ipAddress: "10.0.10.2"
    installDisk: "/dev/sda"
    machineSpec: *spec
    controlPlane: false
    userVolumes:
      - name: longhorn
        provisioning:
          diskSelector:
            match: "!system_disk"
          minSize: 60GiB
          grow: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:52:a9:e5"
        dhcp: false
        addresses:
          - "10.0.10.2/16"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.255.254"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/i915
            - siderolabs/intel-ice-firmware
            - siderolabs/mei
            - siderolabs/xe
            - siderolabs/intel-ucode

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-longhorn.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

