server:
  port: 80
  proxied: true
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezones:
              - timezone: ${TIMEZONE}
                label: CEST Time
          - type: calendar
      - size: full
        widgets:
          - type: search
            search-engine: kagi
            autofocus: true
          - $include: gatus.yml
          - type: videos
            channels:
              - UCGI26U5TLCp43tMfX4y40BA # Bumbles McFumbles
              - UCpFOj1CQMr9a3zaqEfhkTJw # grayfruit
              - UCPd46rZJF4uDUfHWwxtlsQg # DaThings
              - UCCSaQLMqanFT1GkHANX9w2w # cs188
              - UCSOpcUkE-is7u7c4AkLgqTw # MrMobile
          - type: split-column
            widgets:
              - type: hacker-news
                collapse-after: 3
              - type: lobsters
                collapse-after: 3
                sort-by: hot
                tags:
                  - linux
                  - programming
                  - rust
                  - games
                  - graphics
          - type: extension
            url: http://glance-k8s-extension:8080/extension/nodes
            allow-potentially-dangerous-html: true
            cache: 1s
            parameters:
              # namespace, name annotations
              show-if: |
                namespace != kube-system &&
                ("glance/hide" not in annotations || annotations["glance/hide"] != "true")
      - size: small
        widgets:
          - type: weather
            units: metric
            hour-format: 12h
            location: Poznan, Poland
          - type: repository
            repository: zednotdead/gensokyo
            pull-requests-limit: 5
            issues-limit: 3
          - type: monitor
            cache: 1m
            title: Services
            style: compact
            sites:
              - title: Home Assistant
                url: https://ha.${SECRET_DOMAIN}
              - title: Minio
                url: https://minio.${SECRET_DOMAIN}
