server:
  port: 80
  proxied: true
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 12h
            timezones:
              - timezone: ${TIMEZONE}
                label: CEST Time
          - type: calendar
          - type: rss
            limit: 10
            collapse-after: 3
            cache: 3h
            feeds:
              - url: https://flyingsaucervideo.com/comic/feed/
      - size: full
        widgets:
          - type: extension
            url: http://glance-k8s-extension:8080/extension/nodes
            allow-potentially-dangerous-html: true
            cache: 1s
            parameters:
              # namespace, name annotations
              show-if: |
                namespace != kube-system &&
                ("glance/hide" not in annotations || annotations["glance/hide"] != "true")
          - type: hacker-news
          - type: videos
            channels:
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
              - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim
      - size: small
        widgets:
          - type: repository
            repository: zednotdead/gensokyo
            pull-requests-limit: 5
            issues-limit: 3
          - type: monitor
            cache: 1m
            title: Services
            style: compact
            sites:
              - title: Home Assistant
                url: https://hass.ok8.sh
              - title: Grafana
                url: https://grafana.ok8.sh
              - title: BlueMap
                url: https://map.${SECRET_DOMAIN}
