---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./kps/ks.yaml
  - ./grafana/ks.yaml
  - ./pihole-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
