---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr-secret
    creationPolicy: Owner
    template:
      data:
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
  dataFrom:
    - extract:
        key: Sonarr
      rewrite:
      - regexp:
          source: "(.*)"
          target: "SONARR_$1"
    - extract:
        key: Radarr
      rewrite:
      - regexp:
          source: "(.*)"
          target: "RADARR_$1"
