---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./es.yaml
  - ./hr.yaml
configMapGenerator:
  - name: ocis
    files:
      - web.yaml=./config/web.yaml
  - name: ocis-csp
    files:
      - csp.yaml=./config/csp.yaml
generatorOptions:
  disableNameSuffixHash: true
