---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: public-bundle
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: "truenas-ca-secret"
        key: "ca.crt"
  target:
    configMap:
      key: "ca-certificates.crt"
