---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./rook-ceph.yaml
  - ./external-secrets.yaml
  - ./cloudnative-pg.yaml
  - ./node-feature-discovery.yaml
  - ./intel.yaml
  - ./bitnami.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./ext-postgres-operator.yaml
  - ./crunchydata.yaml
  - ./crunchy-userinit.yaml
  - ./authentik.yaml
  - ./prometheus-community.yaml
  - ./grafana.yaml
  - ./fairwinds.yaml
  - ./ananace.yaml
  - ./wrenix.yaml
  - ./nextcloud.yaml
  - ./onlyoffice.yaml
  - ./collabora.yaml
  - ./itzg.yaml
  - ./mariadb.yaml
