---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hoarder
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 5m
  target:
    name: hoarder-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .HOARDER_NEXTAUTH_SECRET }}"
        MEILI_MASTER_KEY: "{{ .HOARDER_MEILI_MASTER_KEY }}"
        NEXT_PUBLIC_SECRET: "{{ .HOARDER_NEXT_PUBLIC_SECRET }}"
        OAUTH_CLIENT_ID: "{{ .HOARDER_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .HOARDER_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: Hoarder
      rewrite:
        - regexp:
            source: "(.*)"
            target: "HOARDER_$1"
