---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage-static
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2

  install:
    remediation:
      retries: 0

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 0

  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: false
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups: [160, 140, 241, 0, 10, 121]

    controllers:
      nginx-static:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/nginxinc/nginx-unprivileged
              tag: "1.27.4"
              pullPolicy: IfNotPresent
            ports:
              - containerPort: 8080

    service:
      app:
        controller: nginx-static
        ports:
          http:
            port: &port 8080

    route:
      main:
        hostnames: ["${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        type: configMap
        name: nginx-config # referenced ConfigMap name
        globalMounts:
          - path: /etc/nginx/nginx.conf
            subPath: nginx.conf # Ensure this matches the key name in the ConfigMap
            readOnly: true
      var:
        type: emptyDir
        globalMounts:
          - path: /var/log/nginx
            subPath: nginx
          - path: /var/cache/nginx
            subPath: nginx
          - path: /var/run
            subPath: run
