---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name unpackerr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        UN_RADARR_0_API_KEY: "{{ .RADARR_API_KEY }}"
        UN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
  - extract:
      key: Radarr
    rewrite:
    - regexp:
        source: "(.*)"
        target: "RADARR_$1"
  - extract:
      key: Sonarr
    rewrite:
    - regexp:
        source: "(.*)"
        target: "SONARR_$1"
