---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
        SMTP_USER: "{{ .SMTP_username }}"
        SMTP_PASSWORD: "{{ .SMTP_password }}"
        SMTP_AUTH_STRATEGY: "TLS"
        SMTP_FROM_EMAIL: mealie@${SECRET_DOMAIN}
        SMTP_FROM_NAME: Mealie
        OIDC_AUTH_ENABLED: "true"
        OIDC_SIGNUP_ENABLED: "true"
        OIDC_CONFIGURATION_URL: "https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration"
        OIDC_CLIENT_ID: "{{ .MEALIE_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MEALIE_CLIENT_SECRET }}"
        OIDC_AUTO_REDIRECT: "false"
        OIDC_REMEMBER_ME: "true"
        OIDC_USER_GROUP: mealie-users
        OIDC_ADMIN_GROUP: mealie-admins
        POSTGRES_USER: &dbUser "{{ .MEALIE_DATABASE_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .MEALIE_DATABASE_PASS }}"
        POSTGRES_SERVER: &dbHost postgres16-rw.database.svc
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        POSTGRES_DB: &dbName miniflux
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: '{{ .CNPG_password }}'
  dataFrom:
    - extract:
        key: Mealie
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MEALIE_$1"
    - extract:
        key: SMTP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SMTP_$1"
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
