apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:GgfOb5i5JA==,iv:VBv4sgmhWWfOeX/5KmVdFVH7fLAVXmY4N6pryXvys+Y=,tag:1LY9JsOOKR4WRqvOL04n7w==,type:str]
sops:
  age:
    - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNmtRSE9WcTJFNjJTeDNv
        WTVZdHJHTE1Qdlc3cjNlZktNT2NhaXFCZ21NCjhZbWRWd3Nxd3doOXQ5cldUSkht
        c2FxUFljb0ZJQ3pFYS84NGhqQlU0L28KLS0tIGcxZW5CSG4wbHlDYTJodjl2cEhK
        V0RreHRyZVp0MFBSUnFxOFpWenRXTGsKjbWoUe/40abh9C3olmdmEeEL2+PpA7Q3
        E4LRe6ry+bxoZehIYpKbsnRH39XtVIeFn98m+bIlUwlQcKPi/EgZCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-21T12:02:27Z"
  mac: ENC[AES256_GCM,data:JLF5O9e+iDBFzgyGosgMWIFvYa0GEFcmrcgSnwxhV02eE2nK3IjsAUCOzNX0Rqww4+5I3lSo0sgYRh/vuFUdA6aaLF/Y6Ym5TW7jj0BFYaq/PqMpKJh27T+yi6aup9taZDH/f3ADe5uYnFjHgbFgsSlaWpmOuiVLfUO1r7OUm5g=,iv:3804ALWEYPMd9YTWjYEDWobFknwNJeanNlrxJKZIFWQ=,tag:AAOcDVvoJNnRR92CFLItnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
