---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      data:
        LLDAP_JWT_SECRET: "{{ .JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LDAP_USER_PASS }}"
        LLDAP_LDAP_BASE_DN: "{{ .LDAP_BASE_DN }}"
        LLDAP_DATABASE_URL: 'postgresql://{{ .DATABASE_USER }}:{{ .DATABASE_PASS }}@postgres16-rw.database.svc:5432/lldap'
        INIT_POSTGRES_DBNAME: lldap
        INIT_POSTGRES_HOST: postgres16-rw.database.svc
        INIT_POSTGRES_USER: "{{ .DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .DATABASE_PASS }}"
        INIT_POSTGRES_SUPER_PASS: '{{ .CNPG_password }}'
  dataFrom:
    - extract:
        key: LLDAP
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
