---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gatus-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
        SECRET_DOMAIN: ${SECRET_DOMAIN}
        POSTGRES_URI: '{{ index . "pgbouncer-uri" }}'
  dataFrom:
  - extract:
      key: Discord
    rewrite:
      - regexp:
          source: "(.*)"
          target: "DISCORD_$1"
  - extract:
      key: postgres-pguser-gatus
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: crunchy-pgo-secrets
